# Generated by Django 5.1.7 on 2025-03-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
